### PR TITLE
define defaultAlphabet as defaultCharacters

### PR DESCRIPTION
**Pull request by ghost**
the defaultAlphabet constant includes numbers and not only letters, better defined as defaultCharacters since you already had `"characters used for generating a password"` stated in `flag.StringVar(&alphabet, "a", defaultAlphabet, "characters used for generating a password")`

### CODE REVIEW

**Comment by nwolber** [comment]
[Alphabet](https://en.wikipedia.org/wiki/Alphabet_%28computer_science%29) is a computer science term used for sets of characters.
The text in the flag.StringVar call is the description shown to the user when passing the -h flag. Thus it is held in non computer science terms. Especially because the alphabet may contain characters other than letters. In fact, it may contain any Unicode character. I will clarify the help message.
Thanks for pointing that out. :+1:

**Comment by ghost** [comment]
oh my mistake lol, sorry man :+1:

**Comment by nwolber** [comment]
No problem. I'm happy about every contribution. :)

**Comment by ghost** [comment]
@nwolber :smile:

**Pull request closed without merging**
